# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  username: satdd
  password: QWERTY$15
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: request_development

test:
  <<: *default
  database: request_test

production:
  <<: *default
  database: request_production
  username: request
  password: <%= ENV['REQUEST_DATABASE_PASSWORD'] %>
